### ISSUE TITLE
Name definition

### ISSUE THREAD

**Issue by marceloboeira** [LosDevs/coatche#2]
Based on Project definition (#1) we need a attractive name.

* Mentor
* Coach
* Jay (JIRA but simple?)
* Dumbledore (since he mentored Harry Potter)

**Comment by gregoriokusowski** [comment]
You've picked coach for the repo, so I see no problems to use it.
Coatch-ê would be funny ![Coatch-ê](http://img2.wikia.nocookie.net/__cb20110506191310/farmville/images/9/97/Yerba_Mate-icon.png)

A mix of Coach and Tchê, our beloved Brazil/RS spoken expression.

**Comment by marceloboeira** [comment]
@gregoriokusowski Perfect! Coatchê!
